n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
resultado = (n1 + n2)
#print('A soma entre', n1, ' e ', n2,' vale',resultado)
print('A soma entre {} e {} vale {}'.format(n1,n2,resultado))